### ISSUE TITLE
Mac wallet fails to open properly

### ISSUE THREAD

**Issue by onestan2** [condominium/CondominiumCore#1]
When attempting to install the wallet on macbook pro, the wallet fails to open.   After multiple tries, it does.

![image](https://user-images.githubusercontent.com/3953634/41263357-13570cd0-6dac-11e8-86b8-b8d9c8aab321.png)

**Comment by chbinvestor** [comment]
me too

**Comment by chbinvestor** [comment]
Can you solve this please?

**Comment by Swissuser** [comment]
Same for me

**Comment by Swissuser** [comment]
V1.2.1.0 and V1.1.0.0 not working

**Comment by steveblackwood** [comment]
I get the feeling they aren't gonna fix this. Two months and counting, and not even an official response?

**Comment by Swissuser** [comment]
Many thanks for your help Condominium ghost team !

**Comment by sfichera** [comment]
Hi, anyone have resolved this one?

**Comment by condominium** [comment]
we just update for mac wallet
