### ISSUE TITLE
Can't pay for myself, nor can I untie it

### ISSUE THREAD

**Issue by elevenjw** [condominium/CondominiumCore#2]
Can't pay for myself, nor can I untie it.
Windows system, mint CDM to zCDM process, abnormal status, unable to pay for yourself.

![_20180613144426](https://user-images.githubusercontent.com/40227713/41334543-9484026e-6f18-11e8-93cc-3a3075c9e8aa.png)

**Comment by condominium** [comment]
you should wait zcdm queue
