### ISSUE TITLE
Multiple Masternodes in 1 wallet.

### ISSUE THREAD

**Issue by Bitdane** [condominium/CondominiumCore#3]
Hey guys, 
I seem to be only getting payouts from 1 masternode even though i have 3 setup.
I only created 1 wallet address for all payments to recieve is this the issue, it has only been running 24 hours do i need to give it more time?
Any tips are very welcome.

Thank you.

**Comment by Arakiss007** [comment]
You need 3 differents adress and 3 differents transactions (3 differents masternode outputs) to prove each masternodes transactions.
Go to the Discord of Condo if you need help : 
https://discord.gg/NRugttx
;-)
