### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by ghost** [condominium/CondominiumCore#4]
I can't open wallet condominium on mac

**Comment by Swissuser** [comment]
Neither. Is there any Dev there ?

**Comment by SoraKohaku** [comment]
issue on bignum code i think since the apple used same debian stretch. on us appear error. for solve this downgrade libssl to 1.0 not 1.1. and this one not work to barkley db 6.3 too. since bitcoin already updates[pixv too]

**Comment by condominium** [comment]
we just update for mac wallet
